### PR TITLE
SQLAlchemy Implementation

### PR DESCRIPTION
**Pull request by kiks12**
Used SQLAlchemy for the database as you said. This is my first time trying a pull request, hope it helps.

### CODE REVIEW

**Comment by nisnevich** [comment]
Hi there! Many thanks for your attention to the project! I'll get back to this next week when I have some time off work. If you could please resolve the conflicts according to the latest changes I'd appreciate. Cheers!

**Comment by kiks12** [comment]
HI! I resolved the conflicts already, nice to meet you sir!

**Comment by nisnevich** [comment]
Thanks so much for the pull request! It really helps, I appreciate.

I wanted to share some notes with you what should be improved in the code. I'll fix it myself after merging because I'll keep going with more changes immediately after, just thought that might be helpful for you to know.

1. Instead of passing the individual attributes of the row to the add_grant_proposal function, the entire object should be passed according to the definition.
2. message_id is a separate column, it was added in the recent changes. id is autogenerated.
3. raw SQL in reactions.py should be changed.
4. some error handling and tests should be added.

Cheers!

**Comment by nisnevich** [comment]
Hello @kiks12! As this project is affiliated with the Eco Community and I applied for a grant to fund its development, I would like to express my gratitude for your contributions through the pull request. Would you be open to receiving a token of appreciation in $ECO to your crypto wallet? Please reach me here or by email: arsnisnevich@gmail.com

**Comment by kiks12** [comment]
Hi there! I received your emails and I'm open to accept your token of appreciation.

**Comment by nisnevich** [comment]
@kiks12 just sent you 5000 $ECO. Thanks again for your input.

**Comment by kiks12** [comment]
Good Day,

I just checked my wallet and I am writing to confirm that I received the
funds. Thank you very much sir!

Have a nice day,
Francis

**Pull request merged**
